### ISSUE TITLE
[Question] What happens when Eureka instance skips a heartbeat against a Eureka server with self preservation turned off?

### ISSUE THREAD

**Issue by narenchoudhary** [Netflix/eureka#1043]
I asked this question on [stackoverflow](https://stackoverflow.com/questions/49128990/what-happens-when-eureka-instance-skips-a-heartbeat-against-a-eureka-server-with). Didn't get much attention (even earned tumbleweed badge). Even added bounty. Still no response. Now posting here.

--- 

Consider this set-up:
* Eureka server with self preservation mode disabled i.e. enableSelfPreservation: false
* 2 Eureka instances each for 2 services (say service#1 and service#2). Total 4 instances.
And one of the instances (say srv#1inst#1, an instance of service#1) sent a heartbeat, but it did not reach the Eureka server.

AFAIK, following actions take place in sequence on Server side:

* ServerStep1: Server observes that a particular instance has missed a heartbeat.
* ServerStep2: Server marks the instance for eviction.
* ServerStep3: Server's eviction scheduler (which runs periodically) evicts the instance from registry.

Now on instance (srv#1inst#1) side:

* InstanceStep1: It skips a heartbeat.
* InstanceStep2: It realizes heartbeat did not reach Eureka Server. It retries with exponential back-off.  

AFAIK, the eviction and registration do not happen immediately. Eureka server runs separate scheduler for both tasks periodically.

I have some questions related to this process:

* Are the sequences correct? If not, what did I miss?
* Is the assumption about eviction and registration scheduler correct?
*  An instance of service#2 requests fresh registry copy from server right after ServerStep2.
    * Will srv#1inst#1 be in the fresh registry copy, because it has not been evicted yet?
        * If yes, will srv#1inst#1 be marked UP or DOWN?
* The retry request from InstanceStep2 of srv#1inst#1 reaches server right after ServerStep2.
    * Will there be an immediate change in registry?
    * How that will affect the response to instance of service#2's request for fresh registry? How will it affect the eviction scheduler?

**Comment by qiangdavidliu** [comment]
Hi @narenchoudhary before I answer the questions specifically, here's some high level information regarding heartbeats and evictions (based on default configs):
1. instances are only marked for eviction if they miss 3 consecutive heartbeats
2. (most) heartbeats do not retry, they are best effort every 30s. The only time a heartbeat will retry is that if there is a threadlevel error on the heartbeating thread (i.e. Timeout or RejectedExecution), but this should be very rare.

 let me try to answer your questions:
- Are the sequences correct? If not, what did I miss?
 A: The sequences are correct, with the above clarifications
- Is the assumption about eviction and registration scheduler correct?
 A: The eviction is handled by an internal scheduler. The registration is processed by the handler thread for the registration request.
- An instance of service#2 requests fresh registry copy from server right after ServerStep2.
  - Will srv#1inst#1 be in the fresh registry copy, because it has not been evicted yet?
    - If yes, will srv#1inst#1 be marked UP or DOWN?
A: There are a few things here:
  - until the instance is actually evicted, it will be part of the result
  - eviction does not involve changing the instance's status, it merely removes the instance from the registry
  - the server holds 30s caches of the state of the world, and it is this cache that's returned. So the exact result as seem by the client, in an eviction scenario, still depends on when it falls within the cache's update cycle.
- The retry request from InstanceStep2 of srv#1inst#1 reaches server right after ServerStep2.
  - Will there be an immediate change in registry?
  - How that will affect the response to instance of service#2's request for fresh registry? How will it affect the eviction scheduler?
A: again a few things:
  - When the actual eviction happen, we check each evictee's time to see if it is eligible to be evicted. If an instance is able to renew its heartbeats before this event, then it is no longer a target for eviction.
  - The 3 events in question (evaluation of eviction eligibility at eviction time, updating the heartbeat status of an instance, generation of the result to be returned to the read operations) all happen asynchronously and their result will depend on the evaluation of the above described criteria at execution time.

Please let me know if you still have more questions.
