### ISSUE TITLE
Eureka in high-available mode throws couple of exceptions when they come up

### ISSUE THREAD

**Issue by thinksky-sourcecode** [Netflix/eureka#1045]
I make it a spring-boot app and enable it as a service-discovery server with Spring-Cloud-Eureka-Server. My purpose is to make it be high-available in 2 instances on 2 different servers. I do it with configuration things and they work well regarding see and sync data. My issue is they always have exceptions in the log in starting phase of apps that said me:

> ReplicationTaskProcessor - Network level connection to peer 10.1.69.110; retrying after delay com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to 10.2.69.72:12050 timed out

My configuration is:

> eureka.instance.hostname=10.1.50.114
> eureka.client.register-with-eureka=true
> eureka.client.fetch-registry=true
> eureka.client.eureka-connection-idle-timeout-seconds=60
> eureka.client.serviceUrl.defaultZone=10.1.69.110:8761/eureka/

After 2 instances come up and see each other, I don't have them (exceptions). I think it should have some configurable items that mention to Eureka please wait for another instance based on millisecond in the startup phase.

**Comment by qiangdavidliu** [comment]
Hi @thinksky-sourcecode thank you for raising the issue. As you correctly state, the errors are transient at start up when multiple servers are being bootstrapped. Since the servers know a priori the hostnames of all of its peers (via config), and there is no guarantee on the order of server start up, it is somewhat difficult to know whether a server should avoid the exceptions at start up. If you have any good suggests, we welcome any PRs. Thanks.

**Comment by qinxiongzhou** [comment]
Hi @qiangdavidliu ,I also encountered this exception. After the eureka cluster has been running for a while, this error is reported from time to time. It is estimated that it will be reported once in three hours. I pinged the server ip, ttl is about 64ms. Do you know what is going on here?
