### ISSUE TITLE
Shared heartbeat for proxied services

### ISSUE THREAD

**Issue by kingo999** [Netflix/eureka#1145]
Hello,
I have a scenario where I have eureka registered micro-services running behind a proxy.
The proxy is a true microservice , it is UP or DOWN.
The sub-services are virtual and created and registered when the proxy is started.
They should use/share the heartbeat of the proxy microservice. All UP or All DOWN.

Is there a way (without custom code) for this scenario to be possible using the supplied Netflix classes/config options (sub-services share heartbeat of proxy) ?
Is there a way to disable a heartbeat for a service permanently other than setting expiry periods so that a service is always up unless told otherwise ?

**Comment by troshko111** [comment]
If I understand your design correctly, you want something like:

1) Have the Proxy heartbeat to Eureka only, do not register the sub-services with Eureka at all as they are not supposed to be independently addressable.

2) In the proxy heartbeat logic, logically `AND` or logically `OR` the sub-service statuses depending on the desired behavior, determine the sub-service statuses by hitting their healthcheck endpoint periodically.

If you wish to just always report `UP` (this is even weaker than doing a logical `OR` of all sub-service healthcheck statuses), you can set up a no-op callback always saying it's `UP` (on the proxy) when registering with Eureka. You must heartbeat anyway even if you're always heartbeating as `UP` unconditionally otherwise your registration will be evicted.

Hope this makes sense.
