### ISSUE TITLE
Eureka Server Down

### ISSUE THREAD

**Issue by shijiyu** [Netflix/eureka#1362]
When Eureka Server Down,EurekaClient can't change locat cache.So when I call DiscoveryClient getInstace(),It still get application instance.

**Comment by troshko111** [comment]
Need more info. What's the behavior you're seeing, expected behavior, steps to reproduce?

**Comment by shijiyu** [comment]
The EurekaClient  gets Applications from Server,when it register to Server.But when Eureka Server is down,or  Network problems,The EurekaClient can't connect to The Eureka Server,The cache of the client can't be refeshed.So when I  use it method getInstance, It still get some instance which status still is up.

**Comment by Iyxh897** [comment]
I also encountered a similar situation.
There are two machines A and B, with EurekaServer deployed on them.The EruekaClient on both machines are registered to these two EurekaServer.
When I unplug the network cable of machine A, EurekaServer B can normally offline all EurekaClient on machine A, and EurekaClient on machine B can pull the correct registry information.After plugging the network cable of machine A back, all services returned to normal.
However, when I unplugged the network cable of machine B, I found that although the EurekaServer on machine A can offline EurekaClient correctly, all the registration information obtained by EurekaClient on machine A has not been updated.

**Comment by troshko111** [comment]
@shijiyu when Eureka client can't connect to Eureka servers, it will not invalidate / purge its local cache _by design_, it is done so that you don't lose critical discovery information in case of Eureka downtime. The information (may) get stale over time, but it's much better to have partially stale information than to have a 100% outage whenever Eureka is down.

@Iyxh897 your issue seems different, I suggest opening a new issue.

**Comment by shijiyu** [comment]
@troshko111 OK,I know,Thanks.
