### ISSUE TITLE
Improvement: optional read only ResponseCache

### ISSUE THREAD

**Issue by brenuart** [Netflix/eureka#536]
It would be nice if the use of the read only response cache could be made optional. Although it seems be useful in some scenarios (see https://github.com/Netflix/eureka/issues/147), it also imposes an additional delay before changes are reflected in the Eureka REST API. This extra delay is very annoying in some deployments.

Is this something that could be foreseen?

**Comment by qiangdavidliu** [comment]
@brenuart this is a feature that we needed internally to help eureka scale to our production usage. It would be useful to have this controllable via a server configuration however. Would you like to make a pull request for this?

**Comment by brenuart** [comment]
I will submit a PR for this.

To be honest, I don't understand why this extra RO cache helps to make performance better. There is already a first cache... why isn't it sufficient? 
I understand the RO cache has the same effect of delaying the invalidations - just like if you applied them in batch of say 100. Is that the objective?

**Comment by qiangdavidliu** [comment]
Hi @brenuart thanks for the pull request. The readonly cache exist as it's a non-expiry based cache compared to the readWriteCache. What we had observed previously was that the increased numbers of 503s (caused due to cache misses on gets as items are expiring) was causing more issues for us due to the scale of usage.

**Comment by qiangdavidliu** [comment]
#544
