### ISSUE TITLE
Improvement: "CacheRefresh" event

### ISSUE THREAD

**Issue by brenuart** [Netflix/eureka#545]
We are looking for a way to be notified when the Eureka client has refresh its local cache. This could help to quickly react on changes in the list of discovered instances, like adapt balancing/routing behaviour.

The `DiscoveryClient` doesn't expose any public/protected method that could be easily overridden to implement such behaviour. However, we were wondering if the `DiscoveryClient` could be enhanced to publish a `CacheRefresh` event on the `eventBus` every time it refreshes its cache?

**Comment by qiangdavidliu** [comment]
@brenuart this would be a useful feature. A simple hook point for this would be to publish this event after every successful execution of the CacheRefreshThread, however this may return some false positives as not every refresh will actually have updates to the local cache. To publish this event only for real changes  may involved some careful hooks to a few different methods (starting point would be the CacheRefreshThread).

Would you be interested in making a pull for this feature?

**Comment by brenuart** [comment]
Some remarks:

(1) First question is what kind of event do we need ?
A `CacheRefreshedEvent` would simply tell the world the cache is refreshed and up-to-date. It doesn't say something has changed. We could leave the change detection to a separate component that would perform the diff and eventually send another event with the change information.

A `CacheUpdateEvent` on the other hand would be sent only if there is a change. But I wonder is if it is useful at all if it doesn't hold information about _what_ has actually changed:
- new instance discovered (which one)?
- instance gone (which one)?
- instance status changed
- etc

It start getting complicated. So my advice would be to go for the simplest `CacheRefreshedEvent` and possibly build a separate listener that would track changes. People interested in the actual delta could use it.


(2) Event or listener?
The second question is whether we should plug into the `eventBus` or go for a simple listener. In the later case, interested parties would register with the `DiscoveryClient` to get the info.
Drawback of the listener pattern: requires component to unregister


(3) Starting hook
According to me, it is probably better to hook into the `fetchRegistry()` method instead of the `CacheRefreshThread`. The `fetchRegistry()` method is where the actual work is done and can/could be invoked from many different places. Currently only at startup and then at regular intervals by the `CacheRefreshThread`. 

Your opinion?

**Comment by brenuart** [comment]
@qiangdavidliu ping?

**Comment by qiangdavidliu** [comment]
@brenuart sorry was busy with other work.

I believe you and I essentially have the same agreement in both of our comments, that is there is two ways to go about this.

The simpler way is to emit events on the cacheRefresh, which gives false positives as not all cache refreshes actually updates data. This is pretty straight forward to add.

The more complex and better way to generate events for real refresh that actually did work is to hook into the various update methods themselves. As the update actions involves deltas and retries the instrumentation point may not be as straight forward.

W.r.t. to the message publishing, using the existing eventBus is nice as a different event (StatusChangeEvent) is already published there. However I have no strong dislikes of a listener, provided that it can be added nicely to the current interface and does not add too much clutter.

Since we don't have a requirement for this feature internally, I leave it to you to decide which route is best for your use case.
