### ISSUE TITLE
DiscoveryClient maintains a STATIC reference to its EurekaClientConfig

### ISSUE THREAD

**Issue by brenuart** [Netflix/eureka#554]
`DiscoveryClient` keeps reference to its `EurekaClientConfig` via a _STATIC_ variable. This may lead to unpredictable behaviour if multiple instances of the client are created.

**Comment by brenuart** [comment]
The `clientConfig` static field is still used by static methods that are now deprecated. Removal of the static is therefore impossible until these methods are actually removed.

In the meantime, it would be useful to add a safe guard in the constructor to check if an instance has already been created and throw an exception otherwise. This would prevent people from creating multiple instances until actually supported.

What do you think?

**Comment by qiangdavidliu** [comment]
Since most of the static methods are deprecated (and the remaining ones are fixable), one way out of this bind is to keep two copies of clientConfig, one static and one instance level. The static clientConfig will be used by the deprecated static methods, and the setting of this will be by each client construction (so slightly undefined as to which version you will get when referenced statically).

**Comment by brenuart** [comment]
Don't you think it might be a better idea to simply prevent multiple instances from being created? I mean, if the the static field is already set, then throw an exception.
The now deprecated static methods are used by clients who assume the singleton pattern anyway - so they are not likely to create multiple instances. And if they do, they are already facing unexpected behaviour.

**Comment by qiangdavidliu** [comment]
If the aim of this is to support multiple instances of DiscoveryClient to be created (for some specific use cases), and the only blocking item is the static client config, then adding exceptions would not be a good user experience, especially since it looks like it's not difficult to make the client config an instance variable of the client itself without compromising the singleton usage of client in the more main stream use case.

**Comment by KishorGrandhe** [comment]
are there any plans and timelines to fix the issue, thanks

**Comment by qiangdavidliu** [comment]
@KishorGrandhe this is on our list of items to fix. If you are interested, a pull request would be very welcome as well. Thanks.

**Comment by Novotarskyi** [comment]
@qiangdavidliu I could try and make a pull request for this one

**Comment by qiangdavidliu** [comment]
This is fixed and now DiscoveryClient instances now have their own config instances. (A static reference still exist for backwards compatibility of some of the existing deprecated static methods, but the static config will be pointing a non-deterministic version of one of the client's instance level config).
