### ISSUE TITLE
Restore HTTP authentication support in eureka client

### ISSUE THREAD

**Issue by tbak** [Netflix/eureka#756]
Check https://github.com/Netflix/eureka/issues/755 for the context.

**Comment by kennedyoliveira** [comment]
Hello! Any news on this topic?

**Comment by tbak** [comment]
Sorry, we have been busy recently. Would you like to make a PR for this?

**Comment by kennedyoliveira** [comment]
I would love to, but don't know how can i make it, if you give me some hints, i don't understand the eureka server, well didn't looked at the source through.

Anyway, i'll try, but would be very helpful if you could give me some advices.

Thank you!

**Comment by YangGuang001** [comment]
i use jks credential, i create it on jvm (build 1.8.0_151-b12),  in the server i use server.keystore,  in the client i use server.cer.
but error message:
Caused by: java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658) ~[na:1.8.0_111]
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[na:1.8.0_111]
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[na:1.8.0_111]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[na:1.8.0_111]

server.keystore:
keytool -validity 365 -genkey -v -alias server -keyalg RSA -keystore server.keystore -dname "CN=127.0.0.1,OU=icesoft,O=icesoft,L=Haidian,ST=Beijing,c=cn" -storepass 123456 -keypass 123456 
server.cer:
keytool -export -v -alias server -keystore server.keystore -storepass 123456 -rfc -file server.cer

```java
@Configuration
public class EurekaJerseyClientAdapter
{
    @Bean
    public EurekaJerseyClient eurekaJerseyClient()
    {
        EurekaJerseyClientImpl.EurekaJerseyClientBuilder builder = new
                EurekaJerseyClientImpl.EurekaJerseyClientBuilder()
                .withTrustStoreFile("server.cer","123456");
        return builder.build();
    }
}
```
