### ISSUE TITLE
API for delete application

### ISSUE THREAD

**Issue by bebepeng** [Netflix/eureka#796]
So we have found ourselves in the situation where somehow the instanceID registered has "http://" in it. We are unable to use the regular delete endpoint to get rid of it.  It would be nice to expose an endpoint that would delete the app or clear all instanceIDs.

**Comment by zgagnon** [comment]
+1

**Comment by qiangdavidliu** [comment]
@bebepeng @zgagnon  sorry for not taking a look at this issue earlier. Can you describe the issue you are seeing in a bit more detail? From what you describe, can I assume the "http://" of the id is what's preventing the DELETE request due to url parsing?

If that is the case, eureka have an internal eviction mechanism where if a heartbeat from a client source is missed for 3 consecutive times (using default config, this would be ~90s), then that entry will be evicted from the registry on the client side. Are you able to shutdown the client with bad instancesIds for that amount of time? If so, that will allow you to evict these client with bad ids.

As for defining instanceIds, as of release 1.2.5 there is a configuration option available to define a custom instanceid for the client instead of sourcing it automatically (see #553), and if you are using the default configuration options, the config setting is eureka.instanceId=some-id

**Comment by zgagnon** [comment]
Have resolved the issue.

Our Eureka instance was in self-preservation mode due to a large number of instances being turned off at once. After manually deleting all extraneous instances that we could, the invalid id instance (http://127.0.0.1) failed its heartbeats and was removed. In this case, a different app had 50+ instances registered at one point (which were all disabled), and after removing them one-by-one, the problem resolved.

With either case, being able to delete the app would have made this a bit easier.

**Comment by qiangdavidliu** [comment]
Glad to hear that issue is resolve on your end. Closing this issue.

W.r.t. an API for application level deletion, agree that it would be useful in some cases. If there is some urgency to the desire of this feature, please feel free to make a PR to add it. Thanks.
