### ISSUE TITLE
Problems getting maven project configured with eureka-client

### ISSUE THREAD

**Issue by dajester2013** [Netflix/eureka#826]
I imported the eureka-client dependency into my maven project, in an attempt to build an app based on http://sparkjava.com (instead of spring) that would register as a client.  I've used https://github.com/Netflix/eureka/tree/master/eureka-examples/src/main/java/com/netflix/eureka as a guide to some degree of success:

The project compiles and runs fine within Eclipse, but trying to compile with maven from the command line fails with something to the effect of "package not found com.netflix.config".  Looking at the client's pom, all of its dependencies are marked runtime.  Apparently, Eclipse is cool with that and uses those dependencies when compiling anyways, however the command-line fails.

What is the best way to get around this?  Actually, what I really want to know is if anyone have a non-spring, maven example project that uses eureka-client to register RESTful services?

**Comment by brharrington** [comment]
For some background on the runtime dependencies issue with nebula, see: https://github.com/nebula-plugins/nebula-publishing-plugin/issues/31

The simplest short term work around I know of would be to just add the dependency directly to your project rather than relying on it being transitive. For `com.netflix.config` specifically, the dependency below provides that package:

https://mvnrepository.com/artifact/com.netflix.archaius/archaius-core/0.7.4

**Comment by dajester2013** [comment]
thanks for the info - i posted a comment there with a suggested fix from the gradle forums.  it's really unfortunate that i either have to use gradle or spend so much time inspecting eureka's (or any other netflix-developed component's) dependency tree and manually configuring my maven dependencies.  that is a complete waste of my time, and speaks very poorly of gradle to me.
