### ISSUE TITLE
How many service instances can one instance of eureka support?

### ISSUE THREAD

**Issue by iamzhout** [Netflix/eureka#834]
I have checked eureka wiki, and not found this kind of information.

Could you please share the performance matrix about Eureka? such as:
1.  How many service instances can one instance of Eureka support?
2.  How many CPU / memory should one eureka use under such condition?
3.  What's the original refresh interval for eureka client in such circumstances, and how many concurrent requests can eureka support, such as xx thousand tps?

Thanks,

**Comment by qiangdavidliu** [comment]
Hi @iamzhout we don't have any exact numbers on the edge limits for eureka, and of course this also is highly dependent on the instance type that the servers are deployed on. To give you a rough idea:

1. eureka servers do not shard their registry, so from a memory footprint p.o.v. all servers will share the same restrictions. Having said that, we have typically found that network I/O being the bounding factor (by far) rather than cpu or memory, especially considering that the network out for queries will increase with the number of instances registered with eureka. 

We run a pretty limited number of servers internally (~10), which serves many 10s of thousands of clients. Having said that, these servers are running on the larger EC2 instance types. If the number of clients reduce, the number of servers can also be reduced.

2. See above regarding network I/O being the bigger bounding factor for eureka servers. Eureka servers does need some baseline amounts of CPU and memory to operate, probably something similar to an EC2 .2xl would be fine.

3. The original (if not overridden) refresh rate is 30seconds.

**Comment by iamzhout** [comment]
Thanks @qiangdavidliu for your reply.

Currently, we are doing some performance test purely on eureka to check its capability and performance in large scale, and found some problems during the process, mainly are:

1.  after registered 100,000 service instances to eureka, and then call delete API (~200 threads concurrently), eureka will be extremely slow of response

2.   after registered 10,000 service instances to eureka, and refresh server list with "/eureka/v2/apps/delta" API every 30 seconds (~200 threads), eureka will slow of response; and the response size is quite large, about 1MB for single request.

What's your suggestion on above performance issue, is it because we didn't call the correct API, use eureka in the right way, or it do have reached the uplimit of eureka itself?  What's the recommended/suitable refresh/hearbeat interval under 100s of thousands service instances?

Thanks,
Tao

**Comment by qiangdavidliu** [comment]
Thanks for the update. I have some questions regarding your set up:
- are you testing with just a single eureka server, or with a cluster set up (and if so, how many instances?)
- with your 200 concurrent calls, are they (relating to the above) hitting the same server or distributed? what is the rate of these calls?

Address your questions without understanding of the two questions above, 

1. We typically run with a cluster set up (~10) as mentioned, so the requests would be shared between these servers. Additionally, we have independent deployments in different regions so the environment itself is effectively sharded.

2. We did encounter this issue as well, and resolve it by adding a readonly proxy fleet internally. There is logic (disabled via configuration) inside eureka-client that handles logic regarding a redirect to only do reads from servers in the readonly fleet. The readonly fleet code has not been open sourced yet, but it is quite straight forward:
```
eureka-server's REST resource -> cache -> eureka-client connecting to write servers
```
see [EurekaTransportConfig.java](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaTransportConfig.java) for the configs as well as javadoc.

Lastly, there are some server side optimizations that we have not enabled by default in OSS configs yet (mainly due to complexity of upgrading an existing deployment with these). 

- One setting you may want to take a look at [this setting](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java#L586) which enables batching for the server to server replication.

- Another is are you using the gzipEncodingEnforcingFilter? This is enabled by default in the provided example web.xml but your set up may be different.

**Comment by qiangdavidliu** [comment]
Closing old issue. Please re-open if necessary.
