### ISSUE TITLE
How can i do with the security tomcat enviroment?

### ISSUE THREAD

**Issue by zyanbingchn** [Netflix/eureka#901]
security tomcat enviroment, that is, the tomcat configured as https.
now, how can i configure to load certification?

if tomcat is https, eureka application service will failed to register service, the error is:
``2017-02-09 15:04:19,957 ERROR com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient:83 [DiscoveryClient-CacheRefreshExecutor-0] [execute] Request execution error
**com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path** to requested target
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
``

**Comment by rrpod** [comment]
Are you using a self-signed certificate? 
Since you are using Tomcat, ensure that you have assigned the keystore in the conf/server.xml file. 
(https://hutter.io/2016/02/09/java-create-self-signed-ssl-certificates-for-tomcat/)

Next for the service which is registering to Eureka, it has to add the self-signed certificate to its truststore. If it is a java application, you can run it with -Djavax.net.ssl.trustStore parameter. 

You can read (https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html) to view the basic keytool commands required to create keystore & import certificates to a truststore.

**Comment by zyanbingchn** [comment]
thank you a lot!
