### ISSUE TITLE
the 90s

### ISSUE THREAD

**Issue by imsandy** [Netflix/eureka#910]
i hava four services a b c d, register to eureka x , and  consumer y call  x ,to call a b c d .

this moment ,i shutdown the service a, the eureka Need 90s to feel the fail.
this 90s my application is Partially unavailable;

英文太差，我写段中文，我有四台机器  a b c d ,注册到注册中心 eureka “x”,有个消费者 y ,通过 x 拿到4个服务的地址，然后我关一台机器a，eureka 需要90s才能感知到 a 已经down了，这90秒我的服务不可用，请问怎么破。

**Comment by zenger380** [comment]
为什么注册一个服务这么慢? (Why is it so Slow to Register a Service?)
Being an instance also involves a periodic heartbeat to the registry (via the client’s serviceUrl) with default duration 30 seconds. A service is not available for discovery by clients until the instance, the server and the client all have the same metadata in their local cache (so it could take 3 heartbeats). You can change the period using eureka.instance.leaseRenewalIntervalInSeconds and this will speed up the process of getting clients connected to other services. In production it’s probably better to stick with the default because there are some computations internally in the server that make assumptions about the lease renewal period.

作为一个实例向注册中心还包括一个默认持续30秒的周期心跳(通过客户的serviceUrl)。一个服务对于客户端的discovery不可用的，直到实例、服务端和客户端全都拥有相同的元数据在它们的缓存里面（这可能还需要3次心跳）。你可以改变使用eureka.instance.leaseRenewalIntervalInSeconds并且这将加快这一进程的客户端连接到其他服务。在实际生产中坚持默认可能是更好的，因为有一些在服务器内部计算对租赁复兴时期做出假设。

**Comment by qiangdavidliu** [comment]
@imsandy are you calling the shutdown method in the client when you shutdown your service? The eureka servers have two ways of removing registered clients:
1. eagerly if a shutdown is received.
2. if a client does not heartbeat for 3 consecutive heartbeats, it is evicted. This case can happen if your service shutdown without calling shutdown on EurekaClient, and leave to a 90s delay.

**Comment by imsandy** [comment]
Thanks for Everybody , i add the retry to the application ,is ok

**Comment by jaychang9** [comment]
@zenger380  @qiangdavidliu 

意思是说服务提供方、服务调用方、eureka服务三方缓存中都有了相同的元数据（应该就是服务提供方地址、端口号、及接口列表信息），才认为服务被注册了吗？但好像还是没有解释为什么是3次心跳，还有哪个需要3次心跳（服务提供方？还是服务调用方？还是eureka注册中心服务）

**Comment by jaychang9** [comment]
@bingge1 How do you understand this problem?Can you describe it
