### ISSUE TITLE
Issue while upgrading Eureka server

### ISSUE THREAD

**Issue by jebeaudet** [Netflix/eureka#930]
Related to https://github.com/Netflix/eureka/issues/929, I created 2 issues so they're clearly divided, hopefully it's fine with you. 

Last upgrade, we had a small downtime with clients complaining there were no instance of an application in their registry (`Load balancer does not have available server for client: foo`). We're using the "Side by side upgrade" mentioned in https://github.com/Netflix/eureka/issues/929. It is the first time we encountered this and I'm trying to trace the issue to understand what happened. There was a misunderstanding in the procedure and the following timeline happened : 

1. Spawn new eureka server
2. When it's up and running, old server is stoped
3. While it's stopping (Still up and receiving heartbeats), the EIP was manually dissasociated in the AWS dashboard
4. New eureka server grabs the released EIP within 1 minute (11:52:35)
5. New eureka server started expiring leases of multiple servers (11:54:36)
6. Old eureka server shutdown completely (11:55:16) 
5. Clients encountered exceptions (11:55:45)

My hypothesis is that once the new server grabbed the EIP, the old continued to receive heartbeats since clients had the connection opened in their pool and did not receive any exception so they continued to use that live connection. Heartbeats/replication did not occured and this eventually lead to the canceling of leases due to the missing heartbeats (we have the self preservation mode off). Is it plausible from your perpective?

Thanks!

**Comment by qiangdavidliu** [comment]
Hi @jebeaudet there are a few potential minor races that can occur when an eureka server has synced but has not assumed an EIP, and what you describe is plausible. There might also be stale registry data in the synced server as while it has not assumed the EIP, it is not receiving up to date replications.

Re the other issue opened, we do our deployments by going sub-par first to avoid any races. We also run with more servers so when sub-par, we still have plenty of redundancy. The system is designed so that going sub-par temporarily is not an issue (as running in AWS, you can lose an instance at any time).
